// ignore_for_file: unnecessary_null_comparison

class AutogeneratedProductModel {
  late List<ProductsResult> products;
  late int total;
  late int skip;
  late int limit;

  AutogeneratedProductModel(
      {required this.products,
      required this.total,
      required this.skip,
      required this.limit});

  AutogeneratedProductModel.fromJson(Map<String, dynamic> json) {
    if (json['products'] != null) {
      products = <ProductsResult>[];
      json['products'].forEach((v) {
        products.add(ProductsResult.fromJson(v));
      });
    }
    total = json['total'];
    skip = json['skip'];
    limit = json['limit'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    if (products != null) {
      data['products'] = products.map((v) => v.toJson()).toList();
    }
    data['total'] = total;
    data['skip'] = skip;
    data['limit'] = limit;
    return data;
  }
}

class ProductsResult {
  late int id;
  late String title;
  late String description;
  late String price;
  late String discountPercentage;
  late String rating;
  late String stock;
  late String brand;
  late String category;
  late String thumbnail;
  late List<String> images;

  ProductsResult(
      {required this.id,
      required this.title,
      required this.description,
      required this.price,
      required this.discountPercentage,
      required this.rating,
      required this.stock,
      required this.brand,
      required this.category,
      required this.thumbnail,
      required this.images});

  ProductsResult.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    title = json['title'];
    description = json['description'];
    price = json['price'];
    discountPercentage = json['discountPercentage'];
    rating = json['rating'];
    stock = json['stock'];
    brand = json['brand'];
    category = json['category'];
    thumbnail = json['thumbnail'];
    images = json['images'].cast<String>();
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['id'] = id;
    data['title'] = title;
    data['description'] = description;
    data['price'] = price;
    data['discountPercentage'] = discountPercentage;
    data['rating'] = rating;
    data['stock'] = stock;
    data['brand'] = brand;
    data['category'] = category;
    data['thumbnail'] = thumbnail;
    data['images'] = images;
    return data;
  }
}
